# Generated by Django 3.1.2 on 2020-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraternity',
            name='applicants',
            field=models.ManyToManyField(blank=True, to='rush.Student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='rush.Student'),
        ),
    ]
